/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuliner;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author acer
 */
public class adminhome extends javax.swing.JFrame {
    private DefaultTableModel model;
    public adminmenuu adminmenuu;
    
    
    /**
     * Creates new form adminhome
     */
    public adminhome() {
        initComponents();
             model = new DefaultTableModel ( );
             menutabel.setModel(model);
             model.addColumn("Nomor");
             model.addColumn("Nama");
             model.addColumn("Isi");
             model.addColumn("Harga"); 
         
        getData();
        
    }
    
    public void getData( ) {
     //menghapus isi table menumakanann
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
           //membuat statemen pemanggilan data pada table menumakanann dari database
           
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/menu?zeroDateTimeBehavior=convertToNull","root","");
           Statement stt = con.createStatement();
           String sql        = "Select * from menumakanan";
           ResultSet res   = stt.executeQuery(sql);

           //penelusuran baris pada tabel menumakanann dari database
           while(res.next ()){
                Object[ ] obj = new Object[4];
                obj[0] = res.getString("Nomor"); 
                obj[1] = res.getString("Nama");
                obj[2] = res.getString("Isi"); 
                obj[3] = res.getString("Harga");
                
                

                model.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menutabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        isi = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        tambahbtn = new javax.swing.JButton();
        btnchange = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        kembalibtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setFont(new java.awt.Font("Rod", 1, 14)); // NOI18N
        jLabel1.setText("MENU PAKET DELIVERY");

        menutabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        menutabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menutabel);

        jLabel2.setText("Nomor");

        jLabel3.setText("Nama Paket");

        jLabel4.setText("Isi Paket");

        jLabel5.setText("Harga");

        btndelete.setText("Hapus Paket");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        tambahbtn.setText("Tambah");
        tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbtnActionPerformed(evt);
            }
        });

        btnchange.setText("Ubah");
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });

        kembalibtn.setText("Kembali");
        kembalibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalibtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kode)
                                    .addComponent(nama)
                                    .addComponent(isi)
                                    .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tambahbtn)
                                .addGap(32, 32, 32)
                                .addComponent(btnchange)
                                .addGap(103, 103, 103)))
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btndelete)
                        .addGap(30, 30, 30)
                        .addComponent(kembalibtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel7)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(isi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahbtn)
                            .addComponent(btnchange))))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(kembalibtn))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbtnActionPerformed
        try {
            
            if (kode.getText().equals("")||nama.getText().equals("")||isi.getText().equals("")||harga.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Masukkan data dengan benar");
                return;
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/menu?zeroDateTimeBehavior=convertToNull","root","");
                Statement stt = con.createStatement();
                String sql        = "Insert into menumakanan (Nomor, Nama, Isi, Harga) values('"+kode.getText()+"','"+nama.getText()+"','"+isi.getText()+"','"+harga.getText()+"')";
                stt.executeUpdate(sql);
           
                kode.setText("");
                nama.setText("");
                isi.setText("");
                harga.setText("");
           
                getData();
                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahbtnActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String x = JOptionPane.showInputDialog(null, "Masukkan Nama yang akan dihapus");
        try {
     
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/menu?zeroDateTimeBehavior=convertToNull","root","");
                Statement stt = con.createStatement();
                String sql = "Delete from menumakanan where Nama = '"+x+"'";
                stt.executeUpdate(sql);
         
                getData();
                JOptionPane.showMessageDialog(null, "Berhasil dihapus");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed
        try {
            
            if (kode.getText().equals("")||nama.getText().equals("")||isi.getText().equals("")||harga.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Masukkan data dengan benar");
                return;
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/menu?zeroDateTimeBehavior=convertToNull","root","");
                Statement stt = con.createStatement();
                String sql = "Update menumakanan set Nama = '"+nama.getText()+"', Isi = '"+isi.getText()+"', Harga = '"+harga.getText()+"' where Nomor = '"+kode.getText()+"'";

          
                PreparedStatement st = con.prepareStatement(sql);
                stt.executeUpdate(sql);
           
                getData();
                kode.setText("");
                nama.setText("");
                isi.setText("");
                harga.setText("");
           
                JOptionPane.showMessageDialog(null, "Berhasil diubah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal diubah");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnchangeActionPerformed

    private void kembalibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalibtnActionPerformed
        adminmenuu = new adminmenuu();
        adminmenuu.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_kembalibtnActionPerformed

    private void menutabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutabelMouseClicked
        kode.setText(menutabel.getValueAt(menutabel.getSelectedRow(), 0).toString());
        nama.setText(menutabel.getValueAt(menutabel.getSelectedRow(), 1).toString());
        isi.setText(menutabel.getValueAt(menutabel.getSelectedRow(), 2).toString());
        harga.setText(menutabel.getValueAt(menutabel.getSelectedRow(), 3).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_menutabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchange;
    private javax.swing.JButton btndelete;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField isi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembalibtn;
    private javax.swing.JTextField kode;
    private javax.swing.JTable menutabel;
    private javax.swing.JTextField nama;
    private javax.swing.JButton tambahbtn;
    // End of variables declaration//GEN-END:variables

}
